version: "3.9"
services:
  web:
    build: ./api/ .
    ports:
      - "5000:80"
      - "5001:443"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - CONNECTIONSTRINGS__DEFAULT=User ID=postgres;Password=postgres;Host=souschef-postgres;Port=27017;Database=postgres
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - "db"
    networks:
      - server-network
  db:
    image: postgres
    container_name: souschef-postgres
    environment:    
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "27018:27017"
    expose:
      - 27017
    networks:
      - server-network
      
networks:
  server-network:
    driver: bridge