import { SvgProps } from "react-native-svg";

const Icons = {
  calendar: require("./calendar.svg").default,
  "check-round": require("./check-round.svg").default,
  check: require("./check.svg").default,
  clipboard: require("./clipboard.svg").default,
  dice: require("./dice.svg").default,
  explore: require("./explore.svg").default,
  group: require("./group.svg").default,
  hide: require("./hide.svg").default,
  home: require("./home.svg").default,
  ingredient: require("./ingredient.svg").default,
  kitchenware: require("./kitchenware.svg").default,
  live: require("./live.svg").default,
  lock: require("./lock.svg").default,
  mail: require("./mail.svg").default,
  "meal-done": require("./meal-done.svg").default,
  meal: require("./meal.svg").default,
  person: require("./person.svg").default,
  qr: require("./qr.svg").default,
  search: require("./search.svg").default,
  show: require("./show.svg").default,
  star: require("./star.svg").default,
  "star-outline": require("./star-outline.svg").default,
  timer: require("./timer.svg").default,
  logo: require("./logo.svg").default,
  "logo-shadow": require("./logo-shadow.svg").default,
  pencil: require("./pencil.svg").default,
  x: require("./x.svg").default,
  "arrow-up": require("./arrow-up.svg").default,
  "arrow-down": require("./arrow-down.svg").default,
  "arrow-left": require("./arrow-left.svg").default,
  "arrow-right": require("./arrow-right.svg").default,
  "back-arrow": require("./back-arrow.svg").default,
  plus: require("./plus.svg").default,
  digit: require("./digit.svg").default,
  retry: require("./retry.svg").default,
  heart: require("./heart.svg").default,
  briefcase: require("./briefcase.svg").default,
  graduationcap: require("./graduationcap.svg").default,
  brochette: require("./brochette.svg").default,
  cake: require("./cake.svg").default,
  menu: require("./menu.svg").default,
  cancel: require("./cancel.svg").default,
  easy: require("./easy.svg").default,
  medium: require("./medium.svg").default,
  hard: require("./hard.svg").default,
  camera: require("./camera.svg").default,
  frame: require("./frame.svg").default,
  "frame-thin": require("./frame-thin.svg").default,
  reload: require("./reload.svg").default,
  logout: require("./logout.svg").default,
  tracker: require("./tracker.svg").default,
  threedots: require("./dots_icon.svg").default,
  "chef-hat": require("./chef-hat.svg").default,
  garbage: require("./garbage.svg").default,
  mic: require("./mic.svg").default,
  "mic-off": require("./mic-off.svg").default,
  // Add more mappings for other SVGs
} as const satisfies Record<string, React.FC<SvgProps>>;

export default Icons;
